# Generated by Django 5.1.7 on 2025-04-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_customer_first_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
