# Generated by Django 5.1.7 on 2025-04-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_transaction_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient_account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
