# Generated by Django 5.1.7 on 2025-04-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_recipient_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient_account',
            name='balance',
        ),
    ]
